# Generated by Django 4.1.7 on 2023-03-17 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.base.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0002_alter_authuser_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.SlugField(max_length=120, verbose_name='Ссылка к жанру')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to=src.base.services.get_upload_path_track, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('link_of_author', models.SlugField(max_length=120)),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('download', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний')),
                ('title_image', models.ImageField(upload_to=src.base.services.get_upload_path_track_image)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='oauth.authuser')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='audio_library.genre')),
            ],
            options={
                'verbose_name': 'Трэк',
                'verbose_name_plural': 'Трэки',
            },
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название плэйлиста')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_lists', to='oauth.authuser')),
                ('tracks', models.ManyToManyField(related_name='track_play_lists', to='audio_library.track')),
            ],
            options={
                'verbose_name': 'Плэйлист',
                'verbose_name_plural': 'Плэйлисты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_comments', to='audio_library.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='oauth.authuser')),
            ],
        ),
    ]
