# Generated by Django 4.1.7 on 2023-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментий', 'verbose_name_plural': 'Комментии'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Ссылка к жанру'),
        ),
    ]
