# Generated by Django 4.1.7 on 2023-03-17 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_authuser_display_name'),
        ('audio_library', '0002_alter_comment_options_alter_genre_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=src.base.services.get_upload_path_track, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название альбома')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('private', models.BooleanField(default=False, verbose_name='Приватный альбом')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=src.base.services.get_upload_path_cover_album, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg']), src.base.services.validate_image_size], verbose_name='Заголовок')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='oauth.authuser')),
            ],
        ),
    ]
