# Generated by Django 4.1.7 on 2023-03-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0003_alter_track_file_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
    ]
