# Generated by Django 4.1.7 on 2023-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_authuser_display_name'),
        ('audio_library', '0005_alter_track_file_alter_track_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='user_of_likes',
            field=models.ManyToManyField(to='oauth.authuser'),
        ),
    ]
