# Generated by Django 4.1.7 on 2023-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_authuser_display_name'),
        ('audio_library', '0007_alter_track_user_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='user_of_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_of_tracks', to='oauth.authuser'),
        ),
    ]
