# Generated by Django 4.1.7 on 2023-03-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0009_track_album_alter_track_user_of_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='title_image',
            new_name='cover',
        ),
    ]
