# Generated by Django 4.1.7 on 2023-03-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0010_rename_title_image_track_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='author',
            new_name='user',
        ),
    ]
