# Generated by Django 4.1.7 on 2023-04-18 09:34

from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0011_rename_author_album_user_rename_owner_playlist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=src.base.services.get_upload_path_track_image, validators=[src.base.services.validate_image_size]),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
