# Generated by Django 4.1.7 on 2023-04-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0012_remove_track_album_alter_track_cover_delete_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
