# Generated by Django 4.1.7 on 2023-04-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0014_alter_track_cover_alter_track_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='audio_library.genre'),
            preserve_default=False,
        ),
    ]
