# Generated by Django 4.1.7 on 2023-04-18 09:34

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_authuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=src.base.services.get_upload_path_avatar, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), src.base.services.validate_image_size], verbose_name='Аватар пользователя'),
        ),
    ]
